import React from 'react'
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion'
import { S05HeadFadeFromBlack } from '../components/S05HeadFadeFromBlack'
import { GAMEPLAY_CLIP_SOURCE } from '../lib/gameplay-clip-source'

/**
 * S05 — Gameplay Dissolve. 18s live-gameplay closer.
 *
 * Absolute frames 2370-2910 (scene-relative 0-540). Hard-cut entry
 * from S04 — S04 owns S04TailFadeToBlack on its tail frames (scene-
 * rel 975-990 = absolute 2355-2370, opacity 0→1). S05 opens with
 * S05HeadFadeFromBlack mandatory pairing (scene-rel 0-15, opacity
 * 1→0). Combined 30-frame fade-through-black is the Archer chapter-
 * break grammar.
 *
 * Pure visual — NO `<Audio>` here. Per ADR #16, all VO cues
 * (s05-cue-2610 sparse Dash + s05-cue-2730 scream) live in
 * TrailerComposition.tsx's composition-level audio map.
 *
 * NO R15 chrome in S05 per BEAT-SHEET §S05 ("clean visual focus for
 * live-gameplay frame"). Iris-wipe transition out lands in Unit 4.8.
 *
 * Gameplay clip is resolved at build time via
 * `gameplay-clip-source.ts` (generated by sync-gameplay-clip script).
 * In Phase 4 this points at gameplay-placeholder.mp4 (looped HTP
 * fullpage capture); Phase 5 ships gameplay.mp4 and the sync hook
 * automatically promotes the constant on next render.
 *
 * Wrapping OffthreadVideo in `<Sequence durationInFrames={540}>` is
 * intentional — surfaces Phase 5 duration drift as a render error
 * (cleaner than silent truncation) per amendment MA-3.
 */
export const S05_GameplayDissolve: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: '#000' }}>
    <Sequence from={0} durationInFrames={540}>
      <OffthreadVideo
        src={staticFile(GAMEPLAY_CLIP_SOURCE)}
        muted
        style={{ width: '100%', height: '100%', objectFit: 'cover' }}
      />
    </Sequence>
    <S05HeadFadeFromBlack endFrame={15} />
  </AbsoluteFill>
)
