/**
 * The bundled ticker → asset-class blend reference table (R37; C1 unit, plan §5).
 *
 * One row per issuer SHARE-CLASS FAMILY (VTI == VTSAX — one strategy, one row): the
 * {stock, bond, cash} allocation intake uses to collapse per-ticker holdings into
 * the single household blend feeding the engine's one `stockWeight` (cash folds into
 * the bond sleeve — the engine is 2-asset, v1; plan §5). Rows are DIRECTIONAL
 * issuer-cited snapshots; SEC EDGAR N-PORT is the independent re-derivation path at
 * the pin pass (DND/012). Target-date funds are STATIC snapshots ("today's
 * allocation, held constant" — the user-facing disclosure string is owned by D1;
 * the years-to-target glide curve is the named correctness upgrade).
 *
 * Allocations are the issuer's OWN figures, never renormalized: a balanced/TDF row
 * may sum to ~97–101 (the issuer's "other" sleeve — preferreds/convertibles — plus
 * rounding); {@link stockWeightForBlend} divides by the actual sum, which
 * distributes the residual pro-rata. An unrecognized ticker returns `undefined`
 * from {@link findBlendRow} — intake routes it to the manual 3-choice classifier
 * (D1); NEVER a default blend (burned/062).
 *
 * Generated programmatically from the C1 research artifact (8-agent two-source
 * verification, 2026-06-10, run wf_9e271ad3) — no hand retyping (insight 018's
 * programmatic-transplant discipline). Two low-confidence rows (SSCKX, JBYSX —
 * inference, not citation) were DROPPED, not guessed; their tickers fall through
 * to the manual classifier until the pin pass sources them from EDGAR.
 *
 * PIN PASS (2026-06-11, run wf_2483859a): all 161 families verified against SEC
 * primaries (485BPOS/N-PORT; issuer page only where no EDGAR registrant exists) —
 * 146 rows stood (6 of those survived adjudication, incl. two where a blind
 * reader mistook reinvested securities-lending cash COLLATERAL for a strategic
 * cash sleeve); 15 rows corrected from the N-PORT/prospectus look-through. PINNED
 * rows store the NORMALIZED look-through as {stock, 100−stock, cash:0} — the raw
 * reconstruction (cash/commodity sleeves, accession) lives in the citation. The
 * numerator convention, uniform: a fund is stock by what it HOLDS — REIT/resource-
 * EQUITY funds are stock (T. Rowe Real Assets, SPDR DJ Global Real Estate);
 * commodity-FUTURES sleeves are not stock and have no third home in a 2-asset
 * engine, so they ride the denominator (≤3.5% on any affected row, recorded
 * per-row). N-PORT assetCat is NEVER trusted for fund-of-funds (it tags bond
 * funds EC) — classification is by underlying-fund <title>.
 */

/** One issuer share-class family's allocation snapshot. */
export interface TickerBlendRow {
  /** ALL tickers in the family (ETF + mutual-fund classes of the same strategy), UPPERCASE. */
  readonly family: readonly string[]
  readonly name: string
  readonly issuer: string
  /** Allocation percentages (0–100), the issuer's own figures (sum ~97–101; see header). */
  readonly stock: number
  readonly bond: number
  readonly cash: number
  /** The issuer product page / fact sheet the allocation was read from. */
  readonly citation: string
  /** False since the 2026-06-11 EDGAR pin pass (161/161 verified); a `true` row is an
   *  unpinned later addition awaiting the next pass. */
  readonly directionalUntilPinned: boolean
  /** Issuer-reported allocation as-of date (meaningful for balanced/TDF rows). */
  readonly asOf?: string
  /** Target-date funds only — the static-snapshot disclosure (D1) keys off this. */
  readonly tdfTargetYear?: number
}

/** The bundled table. ~160 families across the issuers that dominate US retirement
 *  accounts; non-exhaustive BY DESIGN (the manual classifier is the fallback). */
export const TICKER_BLEND_ROWS: readonly TickerBlendRow[] = [
  // ---- Vanguard ----------------------------------------------------------------------
  {
    family: ['VTI', 'VTSAX', 'VTSMX', 'VITSX', 'VSMPX', 'VSTSX'],
    name: 'Vanguard Total Stock Market Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VTI product page — https://investor.vanguard.com/investment-products/etfs/profile/vti (VTSAX: https://investor.vanguard.com/investment-products/mutual-funds/profile/vtsax)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VOO', 'VFIAX', 'VFINX', 'VINIX', 'VIIIX', 'VFFSX'],
    name: 'Vanguard 500 Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VOO product page — https://investor.vanguard.com/investment-products/etfs/profile/voo (VFIAX: https://investor.vanguard.com/investment-products/mutual-funds/profile/vfiax)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VXUS', 'VTIAX', 'VGTSX', 'VTSNX', 'VTPSX'],
    name: 'Vanguard Total International Stock Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VXUS product page — https://investor.vanguard.com/investment-products/etfs/profile/vxus (VTIAX: https://investor.vanguard.com/investment-products/mutual-funds/profile/vtiax)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VT', 'VTWAX', 'VTWIX'],
    name: 'Vanguard Total World Stock Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VT product page — https://investor.vanguard.com/investment-products/etfs/profile/vt (VTWAX: https://investor.vanguard.com/investment-products/mutual-funds/profile/vtwax)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['BND', 'VBTLX', 'VBMFX', 'VBTIX', 'VBMPX'],
    name: 'Vanguard Total Bond Market Index Fund',
    issuer: 'Vanguard',
    stock: 0, bond: 100, cash: 0,
    citation: 'Vanguard BND product page — https://investor.vanguard.com/investment-products/etfs/profile/bnd (VBTLX: https://investor.vanguard.com/investment-products/mutual-funds/profile/vbtlx)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['BNDX', 'VTABX', 'VTIBX', 'VTIFX'],
    name: 'Vanguard Total International Bond Index Fund',
    issuer: 'Vanguard',
    stock: 0, bond: 100, cash: 0,
    citation: 'Vanguard BNDX product page — https://investor.vanguard.com/investment-products/etfs/profile/bndx (VTABX: https://investor.vanguard.com/investment-products/mutual-funds/profile/vtabx)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VTV', 'VVIAX', 'VIVAX', 'VIVIX'],
    name: 'Vanguard Value Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VTV product page — https://investor.vanguard.com/investment-products/etfs/profile/vtv',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VUG', 'VIGAX', 'VIGRX', 'VIGIX'],
    name: 'Vanguard Growth Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VUG product page — https://investor.vanguard.com/investment-products/etfs/profile/vug',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VYM', 'VHYAX'],
    name: 'Vanguard High Dividend Yield Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VYM product page — https://investor.vanguard.com/investment-products/etfs/profile/vym',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VIG', 'VDADX', 'VDAIX'],
    name: 'Vanguard Dividend Appreciation Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VIG product page — https://investor.vanguard.com/investment-products/etfs/profile/vig',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VB', 'VSMAX', 'NAESX', 'VSCIX', 'VSCPX'],
    name: 'Vanguard Small-Cap Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VB product page — https://investor.vanguard.com/investment-products/etfs/profile/vb',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VO', 'VIMAX', 'VIMSX', 'VMCIX', 'VMCPX'],
    name: 'Vanguard Mid-Cap Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VO product page — https://investor.vanguard.com/investment-products/etfs/profile/vo',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VEA', 'VTMGX', 'VDVIX', 'VTMNX'],
    name: 'Vanguard Developed Markets Index Fund (FTSE Developed Markets)',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VEA product page — https://investor.vanguard.com/investment-products/etfs/profile/vea',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VWO', 'VEMAX', 'VEIEX', 'VEMIX'],
    name: 'Vanguard Emerging Markets Stock Index Fund',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VWO product page — https://investor.vanguard.com/investment-products/etfs/profile/vwo',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VNQ', 'VGSLX', 'VGSIX', 'VGSNX'],
    name: 'Vanguard Real Estate Index Fund (REIT)',
    issuer: 'Vanguard',
    stock: 100, bond: 0, cash: 0,
    citation: 'Vanguard VNQ product page — https://investor.vanguard.com/investment-products/etfs/profile/vnq',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VTIP', 'VTAPX', 'VTSPX'],
    name: 'Vanguard Short-Term Inflation-Protected Securities Index Fund',
    issuer: 'Vanguard',
    stock: 0, bond: 100, cash: 0,
    citation: 'Vanguard VTIP product page — https://investor.vanguard.com/investment-products/etfs/profile/vtip',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VGSH', 'VSBSX'],
    name: 'Vanguard Short-Term Treasury Index Fund',
    issuer: 'Vanguard',
    stock: 0, bond: 100, cash: 0,
    citation: 'Vanguard VGSH product page — https://investor.vanguard.com/investment-products/etfs/profile/vgsh',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VGIT', 'VSIGX'],
    name: 'Vanguard Intermediate-Term Treasury Index Fund',
    issuer: 'Vanguard',
    stock: 0, bond: 100, cash: 0,
    citation: 'Vanguard VGIT product page — https://investor.vanguard.com/investment-products/etfs/profile/vgit',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VGLT', 'VLGSX'],
    name: 'Vanguard Long-Term Treasury Index Fund',
    issuer: 'Vanguard',
    stock: 0, bond: 100, cash: 0,
    citation: 'Vanguard VGLT product page — https://investor.vanguard.com/investment-products/etfs/profile/vglt',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VBIAX', 'VBINX', 'VBAIX'],
    name: 'Vanguard Balanced Index Fund',
    issuer: 'Vanguard',
    stock: 61.7, bond: 37.67, cash: 0.63,
    citation: 'Vanguard VBIAX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vbiax (figures from Vanguard\'s fund-profile API allocation feed, api.vanguard.com/rs/ire/01/ind/fund/VBIAX/allocation.json, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VWELX', 'VWENX'],
    name: 'Vanguard Wellington Fund',
    issuer: 'Vanguard',
    stock: 66.62, bond: 32.62, cash: 0.76,
    citation: 'Vanguard VWELX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vwelx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VWINX', 'VWIAX'],
    name: 'Vanguard Wellesley Income Fund',
    issuer: 'Vanguard',
    stock: 38.58, bond: 60.46, cash: 0.96,
    citation: 'Vanguard VWINX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vwinx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VMFXX'],
    name: 'Vanguard Federal Money Market Fund',
    issuer: 'Vanguard',
    stock: 0, bond: 0, cash: 100,
    citation: 'Vanguard VMFXX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vmfxx',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VTINX'],
    name: 'Vanguard Target Retirement Income Fund',
    issuer: 'Vanguard',
    stock: 31.56, bond: 67.79, cash: 0.65,
    citation: 'Vanguard VTINX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vtinx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['VTTVX'],
    name: 'Vanguard Target Retirement 2025 Fund',
    issuer: 'Vanguard',
    stock: 49.35, bond: 50.09, cash: 0.56,
    citation: 'Vanguard VTTVX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vttvx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2025,
  },
  {
    family: ['VTHRX'],
    name: 'Vanguard Target Retirement 2030 Fund',
    issuer: 'Vanguard',
    stock: 60.14, bond: 39.24, cash: 0.62,
    citation: 'Vanguard VTHRX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vthrx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2030,
  },
  {
    family: ['VTTHX'],
    name: 'Vanguard Target Retirement 2035 Fund',
    issuer: 'Vanguard',
    stock: 67.97, bond: 31.46, cash: 0.57,
    citation: 'Vanguard VTTHX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vtthx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2035,
  },
  {
    family: ['VFORX'],
    name: 'Vanguard Target Retirement 2040 Fund',
    issuer: 'Vanguard',
    stock: 75.44, bond: 24.06, cash: 0.5,
    citation: 'Vanguard VFORX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vforx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2040,
  },
  {
    family: ['VTIVX'],
    name: 'Vanguard Target Retirement 2045 Fund',
    issuer: 'Vanguard',
    stock: 82.42, bond: 17.01, cash: 0.57,
    citation: 'Vanguard VTIVX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vtivx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2045,
  },
  {
    family: ['VFIFX'],
    name: 'Vanguard Target Retirement 2050 Fund',
    issuer: 'Vanguard',
    stock: 89.75, bond: 9.74, cash: 0.51,
    citation: 'Vanguard VFIFX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vfifx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2050,
  },
  {
    family: ['VFFVX'],
    name: 'Vanguard Target Retirement 2055 Fund',
    issuer: 'Vanguard',
    stock: 90.48, bond: 9, cash: 0.52,
    citation: 'Vanguard VFFVX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vffvx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2055,
  },
  {
    family: ['VTTSX'],
    name: 'Vanguard Target Retirement 2060 Fund',
    issuer: 'Vanguard',
    stock: 90.48, bond: 8.98, cash: 0.54,
    citation: 'Vanguard VTTSX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vttsx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2060,
  },
  {
    family: ['VLXVX'],
    name: 'Vanguard Target Retirement 2065 Fund',
    issuer: 'Vanguard',
    stock: 90.47, bond: 8.97, cash: 0.56,
    citation: 'Vanguard VLXVX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vlxvx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2065,
  },
  {
    family: ['VSVNX'],
    name: 'Vanguard Target Retirement 2070 Fund',
    issuer: 'Vanguard',
    stock: 90.38, bond: 8.97, cash: 0.65,
    citation: 'Vanguard VSVNX product page — https://investor.vanguard.com/investment-products/mutual-funds/profile/vsvnx (figures from Vanguard\'s fund-profile API allocation feed, as of 2026-04-30)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2070,
  },
  // ---- Fidelity ----------------------------------------------------------------------
  {
    family: ['FXAIX'],
    name: 'Fidelity 500 Index Fund',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity 500 Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FXAIX; cross-checked FT/Morningstar holdings (100.0% stock, 0.0% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FSKAX'],
    name: 'Fidelity Total Market Index Fund',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity Total Market Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FSKAX; cross-checked FT/Morningstar (100.02% stock, -0.02% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FZROX'],
    name: 'Fidelity ZERO Total Market Index Fund',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity ZERO Total Market Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FZROX; cross-checked FT/Morningstar (99.99% stock, 0.01% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FTIHX'],
    name: 'Fidelity Total International Index Fund',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity Total International Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FTIHX; cross-checked FT/Morningstar (99.87% stock + 0.11% other, 0.02% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FZILX'],
    name: 'Fidelity ZERO International Index Fund',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity ZERO International Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FZILX; cross-checked FT/Morningstar (99.84% stock + 0.12% other, 0.05% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FSPSX'],
    name: 'Fidelity International Index Fund',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity International Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FSPSX; cross-checked FT/Morningstar (99.79% stock + 0.16% other, 0.05% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FXNAX'],
    name: 'Fidelity U.S. Bond Index Fund',
    issuer: 'Fidelity',
    stock: 0, bond: 100, cash: 0,
    citation: 'Fidelity U.S. Bond Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FXNAX; cross-checked FT/Morningstar (99.66% bonds, 0.34% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FNILX'],
    name: 'Fidelity ZERO Large Cap Index Fund',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity ZERO Large Cap Index Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/FNILX; cross-checked FT/Morningstar (99.99% stock, 0.01% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FBALX', 'FBAKX'],
    name: 'Fidelity Balanced Fund',
    issuer: 'Fidelity',
    stock: 65.8, bond: 34.2, cash: 0,
    citation: 'Fidelity Balanced Fund composition page — https://fundresearch.fidelity.com/mutual-funds/summary/FBALX (as of 4/30/2026); secondary: Morningstar/Fidelity QFR Q1-2026 (~65% equity / ~35% IG bond average)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FPURX', 'FPUKX'],
    name: 'Fidelity Puritan Fund',
    issuer: 'Fidelity',
    stock: 68.9, bond: 31.1, cash: 0,
    citation: 'Fidelity Puritan Fund composition page — https://fundresearch.fidelity.com/mutual-funds/summary/FPURX (as of 4/30/2026); secondary: AAII fund overview (~63.5% stock / 33.1% bond / 0.8% cash, earlier date)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FCNTX', 'FCNKX'],
    name: 'Fidelity Contrafund',
    issuer: 'Fidelity',
    stock: 99.5, bond: 0, cash: 0.5,
    citation: 'Fidelity Contrafund composition page — https://fundresearch.fidelity.com/mutual-funds/summary/FCNTX (4/30/2026: 90.32% domestic + 9.18% intl equity, 0.00% bonds, 0.50% cash); secondary: Morningstar 3/31/2026 (85.0% US + 7.9% non-US + 6.2% other, 0.9% cash)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['FDVV'],
    name: 'Fidelity High Dividend ETF',
    issuer: 'Fidelity',
    stock: 100, bond: 0, cash: 0,
    citation: 'Fidelity High Dividend ETF page — https://institutional.fidelity.com/app/funds-and-products/etf/snapshot/FIIS_ETF_FDVV.html; cross-checked FT/Morningstar holdings (94.17% US + 5.56% non-US stock = 99.73% equity, net cash+other ~0.3% as of 5/29/2026)',
    directionalUntilPinned: false,
    asOf: '2026-05-29',
  },
  {
    family: ['SPAXX', 'FZCXX'],
    name: 'Fidelity Government Money Market Fund',
    issuer: 'Fidelity',
    stock: 0, bond: 0, cash: 100,
    citation: 'Fidelity Government Money Market Fund page — https://fundresearch.fidelity.com/mutual-funds/summary/SPAXX (invests ≥99.5% in cash, US government securities and repos); FZCXX Premium Class verified via Fidelity fund pages',
    directionalUntilPinned: false,
    asOf: '2026-06-10',
  },
  {
    family: ['FDRXX'],
    name: 'Fidelity Government Cash Reserves',
    issuer: 'Fidelity',
    stock: 0, bond: 0, cash: 100,
    citation: 'Fidelity Government Cash Reserves page — https://fundresearch.fidelity.com/mutual-funds/summary/FDRXX',
    directionalUntilPinned: false,
    asOf: '2026-06-10',
  },
  {
    family: ['FIKFX'],
    name: 'Fidelity Freedom Index Retirement Fund (formerly Freedom Index Income)',
    issuer: 'Fidelity',
    stock: 22.53, bond: 77.47, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000026411 acc 0000035402-26-003364 (period 2026-03-31), FoF reconstructed by underlying <title> (all EC-mistagged): stock 22.49 (Total Mkt 13.67 + Global ex-US 8.82) / bond 68.10 / cash 8.23 / commodity 1.02, raw sum 99.84; normalized, commodity+cash in denominator. NOTE: glide-revision transition in flight (Q4-2025→Q1-2027, revised neutral ~28% equity; the issuer 4/30 look-through reads 27.15) — re-pin next pass',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['FQIFX'],
    name: 'Fidelity Freedom Index 2025 Fund',
    issuer: 'Fidelity',
    stock: 49.52, bond: 50.48, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000026416 acc 0000035402-26-003373 (period 2026-03-31), FoF by <title>: stock 49.47 (Total Mkt 30.11 + Global ex-US 19.36) / bond 50.16 / cash 0.26, raw sum 99.89; normalized. Same glide-revision transition as FIKFX — re-pin next pass',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2025,
  },
  {
    family: ['FXIFX'],
    name: 'Fidelity Freedom Index 2030 Fund',
    issuer: 'Fidelity',
    stock: 56.06, bond: 43.94, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000026417 acc 0000035402-26-003378 (period 2026-03-31), FoF by <title>: stock 56.00 (Total Mkt 34.10 + Global ex-US 21.90) / bond 43.90, raw sum 99.90; normalized. Same glide-revision transition as FIKFX — re-pin next pass',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2030,
  },
  {
    family: ['FIHFX'],
    name: 'Fidelity Freedom Index 2035 Fund',
    issuer: 'Fidelity',
    stock: 67.2, bond: 32.8, cash: 0.1,
    citation: 'Fidelity Freedom Index 2035 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FIHFX (40.34/26.82/32.76/0.08); independently verified via underlying-fund holdings (stockanalysis.com, 4/30/2026, exact match)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2035,
  },
  {
    family: ['FBIFX'],
    name: 'Fidelity Freedom Index 2040 Fund',
    issuer: 'Fidelity',
    stock: 81.4, bond: 18.5, cash: 0.1,
    citation: 'Fidelity Freedom Index 2040 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FBIFX (48.87/32.56/18.53/0.04); independently verified via underlying-fund holdings (stockanalysis.com, 4/30/2026, exact match)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2040,
  },
  {
    family: ['FIOFX'],
    name: 'Fidelity Freedom Index 2045 Fund',
    issuer: 'Fidelity',
    stock: 90.6, bond: 9.4, cash: 0,
    citation: 'Fidelity Freedom Index 2045 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FIOFX (54.40/36.22/9.36/0.02); independently verified via underlying-fund holdings (stockanalysis.com, 4/30/2026, exact match)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2045,
  },
  {
    family: ['FIPFX'],
    name: 'Fidelity Freedom Index 2050 Fund',
    issuer: 'Fidelity',
    stock: 92, bond: 8, cash: 0,
    citation: 'Fidelity Freedom Index 2050 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FIPFX (55.24/36.79/7.95/0.02); independently verified via underlying-fund holdings (stockanalysis.com, 4/30/2026, exact match)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2050,
  },
  {
    family: ['FDEWX'],
    name: 'Fidelity Freedom Index 2055 Fund',
    issuer: 'Fidelity',
    stock: 93.4, bond: 6.6, cash: 0,
    citation: 'Fidelity Freedom Index 2055 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FDEWX (56.07/37.30/6.62/0.01); independently verified via underlying-fund holdings (stockanalysis.com, 4/30/2026, exact match)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2055,
  },
  {
    family: ['FDKLX'],
    name: 'Fidelity Freedom Index 2060 Fund',
    issuer: 'Fidelity',
    stock: 93.6, bond: 6.4, cash: 0,
    citation: 'Fidelity Freedom Index 2060 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FDKLX (56.18/37.39/6.42/0.01); independently verified via underlying-fund holdings (stockanalysis.com, 4/30/2026: 56.18 US eq + 37.39 intl eq + 1.53+4.50+0.39 bonds + 0.01 cash, exact match)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2060,
  },
  {
    family: ['FFIJX'],
    name: 'Fidelity Freedom Index 2065 Fund',
    issuer: 'Fidelity',
    stock: 93.6, bond: 6.4, cash: 0,
    citation: 'Fidelity Freedom Index 2065 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FFIJX (56.18/37.39/6.42/0.01); independently verified via underlying-fund holdings (stockanalysis.com, 4/30/2026, exact match)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2065,
  },
  {
    family: ['FFFAX'],
    name: 'Fidelity Freedom Retirement Fund (formerly Freedom Income) — ACTIVE series',
    issuer: 'Fidelity',
    stock: 28.1, bond: 71.9, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000004876 acc 0000035402-26-003380 (period 2026-03-31), FoF by <title>: stock 28.08 / bond 64.10 / cash 5.95 / commodity 1.76, raw sum 99.88; normalized. CROSS-CONFIRMED by the 485BPOS revised stable-neutral allocation (~17 US + 11 intl = 28% equity, transition complete by Q1-2027) — two SEC primaries agree; the issuer page 33% conflicted with both',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['FFTWX'],
    name: 'Fidelity Freedom 2025 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 56.3, bond: 43.7, cash: 0,
    citation: 'Fidelity Freedom 2025 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FFTWX (raw 4/30/2026: 32.37% US eq + 26.30% non-US eq / 45.54% bonds / -4.21% short-term & net other); secondary: FT/Morningstar look-through 4/30/2026 normalizes to ~55.9/44.1',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2025,
  },
  {
    family: ['FFFEX'],
    name: 'Fidelity Freedom 2030 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 62.4, bond: 37.6, cash: 0,
    citation: 'Fidelity Freedom 2030 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FFFEX (raw 4/30/2026: 36.22 + 28.81 / 39.12 / -4.15); secondary: FT/Morningstar look-through 4/30/2026 (62.4 stock / 38.6 bond / -1.8 cash, normalized ~61.8/38.2)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2030,
  },
  {
    family: ['FFTHX'],
    name: 'Fidelity Freedom 2035 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 69.9, bond: 30.1, cash: 0,
    citation: 'Fidelity Freedom 2035 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FFTHX (raw 4/30/2026: 40.92 + 31.86 / 31.36 / -4.14); secondary: FT/Morningstar look-through 4/30/2026 (69.9 stock / 30.9 bond / -1.8 cash)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2035,
  },
  {
    family: ['FFFFX'],
    name: 'Fidelity Freedom 2040 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 83.3, bond: 16.7, cash: 0,
    citation: 'Fidelity Freedom 2040 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FFFFX (raw 4/30/2026: 49.40 + 37.35 / 17.40 / -4.15); secondary: FT/Morningstar look-through 4/30/2026 (83.4 stock / 17.1 bond / -1.7 cash)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2040,
  },
  {
    family: ['FFFGX'],
    name: 'Fidelity Freedom 2045 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 91.2, bond: 8.8, cash: 0,
    citation: 'Fidelity Freedom 2045 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FFFGX (raw 4/30/2026: 54.68 + 40.92 / 9.27 / -4.87); secondary: FT/Morningstar look-through 4/30/2026 (92.0 stock / 9.1 bond / -2.4 cash, normalized ~91.1/8.9)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2045,
  },
  {
    family: ['FFFHX'],
    name: 'Fidelity Freedom 2050 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 92, bond: 8, cash: 0,
    citation: 'Fidelity Freedom 2050 composition — https://fundresearch.fidelity.com/mutual-funds/summary/FFFHX (raw 4/30/2026: 55.42 + 41.40 / 8.43 / -5.25); secondary: FT/Morningstar look-through 4/30/2026 (93.0 stock / 8.3 bond / -2.7 cash)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2050,
  },
  {
    family: ['FDEEX'],
    name: 'Fidelity Freedom 2055 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 96.2, bond: 3.8, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000032801 acc 0000035402-26-003336 (period 2026-03-31), FoF by <title>: stock 96.15 / bond 2.58 / cash 0.43 / commodity 0.76, raw sum 99.91; normalized, commodity+cash in denominator',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2055,
  },
  {
    family: ['FDKVX'],
    name: 'Fidelity Freedom 2060 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 96.5, bond: 3.5, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000046197 acc 0000035402-26-003349 (period 2026-03-31), FoF by <title>: stock 96.40 / bond 2.33 / cash 0.42 / commodity 0.76, raw sum 99.91; normalized, commodity+cash in denominator',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2060,
  },
  {
    family: ['FFSFX', 'FFSDX', 'FFSZX'],
    name: 'Fidelity Freedom 2065 Fund (ACTIVE series)',
    issuer: 'Fidelity',
    stock: 96.5, bond: 3.5, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000065624 acc 0000035402-26-003332 (period 2026-03-31; FFSFX/FFSDX/FFSZX = three classes of ONE series, confirmed via company_tickers_mf.json), FoF by <title>: stock 96.42 / bond 2.33 / cash 0.41 / commodity 0.76, raw sum 99.91; normalized',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2065,
  },
  // ---- Schwab ------------------------------------------------------------------------
  {
    family: ['SWPPX'],
    name: 'Schwab S&P 500 Index Fund',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/swppx (cross-checked: Fidelity fund research, AAII, FT.com)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['SWTSX'],
    name: 'Schwab Total Stock Market Index Fund',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/swtsx (cross-checked: Fidelity fund research, AAII)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['SCHB'],
    name: 'Schwab U.S. Broad Market ETF',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/schb (Schwab page: 99.96% stocks / 0.04% cash as of 6/9/2026; cross-checked AAII, etf.com)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SCHX'],
    name: 'Schwab U.S. Large-Cap ETF',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/schx (Schwab page: 99.93% stocks / 0.07% cash as of 6/9/2026; cross-checked etf.com, FT.com)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SCHD'],
    name: 'Schwab U.S. Dividend Equity ETF',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/schd (Schwab page: 99.90% stocks / 0.10% cash as of 6/9/2026; cross-checked Fidelity 0.08% cash 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SCHF'],
    name: 'Schwab International Equity ETF',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/schf (Schwab page: 99.77% stocks / 0.23% cash as of 6/9/2026; cross-checked etf.com)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SCHE'],
    name: 'Schwab Emerging Markets Equity ETF',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/sche (cross-checked FT.com ~1.17% cash, etf.com)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SCHG'],
    name: 'Schwab U.S. Large-Cap Growth ETF',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/schg (Schwab page: 99.97% stocks / 0.03% cash as of 6/9/2026; cross-checked Fidelity 0.07% cash 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SCHV'],
    name: 'Schwab U.S. Large-Cap Value ETF',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/schv (Schwab page: 99.92% stocks / 0.08% cash as of 6/9/2026; cross-checked etf.com)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SWISX'],
    name: 'Schwab International Index Fund',
    issuer: 'Schwab',
    stock: 100, bond: 0, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/swisx (cross-checked AAII, FT.com: ~0.4% cash as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['SWAGX', 'SCHZ'],
    name: 'Schwab U.S. Aggregate Bond Index (mutual fund SWAGX + ETF SCHZ, same Bloomberg US Aggregate strategy)',
    issuer: 'Schwab',
    stock: 0, bond: 100, cash: 0,
    citation: 'Schwab Asset Management product pages — https://www.schwabassetmanagement.com/products/swagx and https://www.schwabassetmanagement.com/products/schz (cross-checked AAII, Morningstar: SCHZ 98.8% bonds / 1.18% cash as of 6/2/2026; SWAGX 98.3% bonds / 1.7% cash Apr 2026)',
    directionalUntilPinned: false,
    asOf: '2026-06-02',
  },
  {
    family: ['SCHO'],
    name: 'Schwab Short-Term U.S. Treasury ETF',
    issuer: 'Schwab',
    stock: 0, bond: 100, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/scho (Schwab page: 100.00% government bonds as of 6/9/2026; cross-checked AAII 99.9% bond / 0.1% cash Apr 2026)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SCHR'],
    name: 'Schwab Intermediate-Term U.S. Treasury ETF',
    issuer: 'Schwab',
    stock: 0, bond: 100, cash: 0,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/schr (Schwab page: 99.97% government bonds / 0.03% cash as of 6/9/2026; cross-checked AAII)',
    directionalUntilPinned: false,
    asOf: '2026-06-09',
  },
  {
    family: ['SWVXX', 'SNAXX'],
    name: 'Schwab Value Advantage Money Fund',
    issuer: 'Schwab',
    stock: 0, bond: 0, cash: 100,
    citation: 'Schwab Asset Management product page — https://www.schwabassetmanagement.com/products/swvxx (cross-checked Schwab money fund overview, AAII)',
    directionalUntilPinned: false,
    asOf: '2026-06-10',
  },
  {
    family: ['SWYDX'],
    name: 'Schwab Target 2025 Index Fund',
    issuer: 'Schwab',
    stock: 43.7, bond: 53.6, cash: 2.7,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swydx (allocation snapshot cross-verified on Fidelity fund research and AAII: 33.09% domestic + 10.61% foreign stock; 50.66% domestic + 2.90% foreign bond; 2.72% cash, as of 3/31/2026)',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2025,
  },
  {
    family: ['SWYEX'],
    name: 'Schwab Target 2030 Index Fund',
    issuer: 'Schwab',
    stock: 56.2, bond: 41.5, cash: 2.2,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swyex (cross-verified Fidelity/AAII: 40.75% domestic + 15.45% foreign stock; 39.07% domestic + 2.46% foreign bond; 2.24% cash, as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2030,
  },
  {
    family: ['SWYFX'],
    name: 'Schwab Target 2035 Index Fund',
    issuer: 'Schwab',
    stock: 67.6, bond: 30.5, cash: 1.9,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swyfx (cross-verified AAII/Fidelity: 47.9% domestic + 19.7% foreign stock; 28.5% domestic + 2.0% foreign bond; 1.9% cash, as of 5/31/2026)',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2035,
  },
  {
    family: ['SWYGX'],
    name: 'Schwab Target 2040 Index Fund',
    issuer: 'Schwab',
    stock: 76.3, bond: 22.2, cash: 1.5,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swygx (cross-verified Fidelity/AAII: 53.09% domestic + 23.18% foreign stock; 20.69% domestic + 1.48% foreign bond; 1.53% cash, as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2040,
  },
  {
    family: ['SWYHX'],
    name: 'Schwab Target 2045 Index Fund',
    issuer: 'Schwab',
    stock: 83.4, bond: 15.2, cash: 1.4,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swyhx (cross-verified AAII/Fidelity: 57.1% domestic + 26.3% foreign stock; 14.2% domestic + 1.0% foreign bond; 1.4% cash, as of 5/31/2026)',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2045,
  },
  {
    family: ['SWYMX'],
    name: 'Schwab Target 2050 Index Fund',
    issuer: 'Schwab',
    stock: 89.1, bond: 9.9, cash: 1,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swymx (cross-verified Fidelity/AAII: 60.29% domestic + 28.77% foreign stock = 89.06%; 9.20% domestic + 0.68% foreign bond = 9.88%; 1.01% cash, as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2050,
  },
  {
    family: ['SWYJX'],
    name: 'Schwab Target 2055 Index Fund',
    issuer: 'Schwab',
    stock: 92.3, bond: 6.8, cash: 0.9,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swyjx (cross-verified Fidelity/AAII: 61.94% domestic + 30.34% foreign stock = 92.28%; 6.36% domestic + 0.47% foreign bond = 6.83%; 0.85% cash, as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2055,
  },
  {
    family: ['SWYNX'],
    name: 'Schwab Target 2060 Index Fund',
    issuer: 'Schwab',
    stock: 94.3, bond: 4.9, cash: 0.8,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swynx (cross-verified Fidelity/AAII: 62.94% domestic + 31.36% foreign stock = 94.30%; 4.53% domestic + 0.34% foreign bond = 4.87%; 0.78% cash, as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2060,
  },
  {
    family: ['SWYOX'],
    name: 'Schwab Target 2065 Index Fund',
    issuer: 'Schwab',
    stock: 96.1, bond: 2.9, cash: 0.9,
    citation: 'Schwab Asset Management product page / fact sheet — https://www.schwabassetmanagement.com/products/swyox (cross-verified Fidelity/AAII: 63.7% domestic + 32.4% foreign stock = 96.1%; 2.7% domestic + 0.2% foreign bond = 2.9%; 0.9% cash, as of 4/30/2026)',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2065,
  },
  // ---- iShares (BlackRock) / SPDR (State Street) / Invesco ---------------------------
  {
    family: ['IVV'],
    name: 'iShares Core S&P 500 ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239726/ishares-core-sp-500-etf (page title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['ITOT'],
    name: 'iShares Core S&P Total U.S. Stock Market ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239724/ishares-core-sp-total-us-stock-market-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['IWM'],
    name: 'iShares Russell 2000 ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239710/ishares-russell-2000-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['IWB'],
    name: 'iShares Russell 1000 ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239707/ishares-russell-1000-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['IWD'],
    name: 'iShares Russell 1000 Value ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239708/ishares-russell-1000-value-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['IWF'],
    name: 'iShares Russell 1000 Growth ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239706/ishares-russell-1000-growth-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['EFA'],
    name: 'iShares MSCI EAFE ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239623/ishares-msci-eafe-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['IEFA'],
    name: 'iShares Core MSCI EAFE ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/244049/ishares-core-msci-eafe-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['IEMG'],
    name: 'iShares Core MSCI Emerging Markets ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/244050/ishares-core-msci-emerging-markets-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['EEM'],
    name: 'iShares MSCI Emerging Markets ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239637/ishares-msci-emerging-markets-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['DGRO'],
    name: 'iShares Core Dividend Growth ETF',
    issuer: 'BlackRock iShares',
    stock: 100, bond: 0, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/264623/ishares-core-dividend-growth-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['AGG'],
    name: 'iShares Core U.S. Aggregate Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239458/ishares-core-total-us-bond-market-etf (title verified live 2026-06-10: \'iShares Core U.S. Aggregate Bond ETF | AGG\')',
    directionalUntilPinned: false,
  },
  {
    family: ['IUSB'],
    name: 'iShares Core Universal USD Bond ETF (formerly iShares Core Total USD Bond Market ETF)',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/264615/ishares-core-total-usd-bond-market-etf (title verified live 2026-06-10: \'iShares Core Universal USD Bond ETF | IUSB\')',
    directionalUntilPinned: false,
  },
  {
    family: ['TLT'],
    name: 'iShares 20+ Year Treasury Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239454/ishares-20-year-treasury-bond-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['IEF'],
    name: 'iShares 7-10 Year Treasury Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239456/ishares-710-year-treasury-bond-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['SHY'],
    name: 'iShares 1-3 Year Treasury Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239452/ishares-13-year-treasury-bond-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['GOVT'],
    name: 'iShares U.S. Treasury Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239468/ishares-us-treasury-bond-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['LQD'],
    name: 'iShares iBoxx $ Investment Grade Corporate Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239566/ishares-iboxx-investment-grade-corporate-bond-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['TIP'],
    name: 'iShares TIPS Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 100, cash: 0,
    citation: 'iShares product page: https://www.ishares.com/us/products/239467/ishares-tips-bond-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['SGOV'],
    name: 'iShares 0-3 Month Treasury Bond ETF',
    issuer: 'BlackRock iShares',
    stock: 0, bond: 0, cash: 100,
    citation: 'iShares product page: https://www.ishares.com/us/products/314116/ishares-0-3-month-treasury-bond-etf (title verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['AOK'],
    name: 'iShares Core 30/70 Conservative Allocation ETF (renamed from iShares Core Conservative Allocation ETF, 2025-02-19)',
    issuer: 'BlackRock iShares',
    stock: 30.03, bond: 69.01, cash: 0.97,
    citation: 'iShares fact sheet (Asset Type Breakdown, as of 2026-03-31): https://www.ishares.com/us/literature/fact-sheet/aok-ishares-core-30-70-conservative-allocation-etf-fund-fact-sheet-en-us.pdf ; product page https://www.ishares.com/us/products/239733/ (title verified)',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['AOM'],
    name: 'iShares Core 40/60 Moderate Allocation ETF (renamed from iShares Core Moderate Allocation ETF, 2025-02-19)',
    issuer: 'BlackRock iShares',
    stock: 39.98, bond: 59.09, cash: 0.93,
    citation: 'iShares fact sheet (Asset Type Breakdown, as of 2026-03-31): https://www.ishares.com/us/literature/fact-sheet/aom-ishares-core-40-60-moderate-allocation-etf-fund-fact-sheet-en-us.pdf ; product page https://www.ishares.com/us/products/239765/ (title verified)',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['AOR'],
    name: 'iShares Core 60/40 Balanced Allocation ETF (renamed from iShares Core Growth Allocation ETF, 2025-02-19)',
    issuer: 'BlackRock iShares',
    stock: 59.9, bond: 39.35, cash: 0.75,
    citation: 'iShares fact sheet (Asset Type Breakdown, as of 2026-03-31): https://www.ishares.com/us/literature/fact-sheet/aor-ishares-core-60-40-balanced-allocation-etf-fund-fact-sheet-en-us.pdf ; product page https://www.ishares.com/us/products/239756/ (title verified)',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['AOA'],
    name: 'iShares Core 80/20 Aggressive Allocation ETF (renamed from iShares Core Aggressive Allocation ETF, 2025-02-19)',
    issuer: 'BlackRock iShares',
    stock: 79.7, bond: 19.75, cash: 0.56,
    citation: 'iShares fact sheet (Asset Type Breakdown, as of 2026-03-31): https://www.ishares.com/us/literature/fact-sheet/aoa-ishares-core-80-20-aggressive-allocation-etf-fund-fact-sheet-en-us.pdf ; product page https://www.ishares.com/us/products/239729/ (title verified)',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['SPY', 'SPLG', 'SPYM'],
    name: 'State Street S&P 500 family: SPDR S&P 500 ETF Trust (SPY) + State Street SPDR Portfolio S&P 500 ETF (SPLG, re-tickered SPYM effective 2025-10-31)',
    issuer: 'State Street (SPDR)',
    stock: 100, bond: 0, cash: 0,
    citation: 'SSGA product pages: https://www.ssga.com/us/en/individual/etfs/state-street-spdr-sp-500-etf-trust-spy and https://www.ssga.com/us/en/individual/etfs/state-street-spdr-portfolio-sp-500-etf-spym (both verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['DIA'],
    name: 'SPDR Dow Jones Industrial Average ETF Trust',
    issuer: 'State Street (SPDR)',
    stock: 100, bond: 0, cash: 0,
    citation: 'SSGA product page: https://www.ssga.com/us/en/individual/etfs/state-street-spdr-dow-jones-industrial-average-etf-trust-dia (verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['BIL'],
    name: 'SPDR Bloomberg 1-3 Month T-Bill ETF',
    issuer: 'State Street (SPDR)',
    stock: 0, bond: 0, cash: 100,
    citation: 'SSGA product page: https://www.ssga.com/us/en/individual/etfs/state-street-spdr-bloomberg-1-3-month-t-bill-etf-bil (verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['QQQ', 'QQQM'],
    name: 'Invesco Nasdaq-100 family: Invesco QQQ Trust (QQQ) + Invesco NASDAQ 100 ETF (QQQM)',
    issuer: 'Invesco',
    stock: 100, bond: 0, cash: 0,
    citation: 'Invesco product pages: https://www.invesco.com/qqq-etf/en/home.html and https://www.invesco.com/us/en/financial-products/etfs/invesco-nasdaq-100-etf.html (both verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  {
    family: ['RSP'],
    name: 'Invesco S&P 500 Equal Weight ETF',
    issuer: 'Invesco',
    stock: 100, bond: 0, cash: 0,
    citation: 'Invesco product page: https://www.invesco.com/us/en/financial-products/etfs/invesco-sp-500-equal-weight-etf.html (verified live 2026-06-10)',
    directionalUntilPinned: false,
  },
  // ---- Other major 401(k) families (T. Rowe / American Funds / State Street / JPMorgan) ----
  {
    family: ['TRRHX', 'TRPHX'],
    name: 'T. Rowe Price Retirement 2025 Fund (Investor + I class)',
    issuer: 'T. Rowe Price',
    stock: 53.2, bond: 40.5, cash: 6,
    citation: 'T. Rowe Price fund page/fact sheet — https://www.troweprice.com/personal-investing/tools/fund-research/TRRHX ; figures per Morningstar/AAII look-through — https://www.morningstar.com/funds/xnas/trrhx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2025,
  },
  {
    family: ['TRRCX', 'TRPCX'],
    name: 'T. Rowe Price Retirement 2030 Fund',
    issuer: 'T. Rowe Price',
    stock: 61.4, bond: 33.1, cash: 5.1,
    citation: 'T. Rowe Price fund page — https://www.troweprice.com/personal-investing/tools/fund-research/TRRCX ; figures per Morningstar portfolio — https://www.morningstar.com/funds/xnas/trrcx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2030,
  },
  {
    family: ['TRRJX', 'TRPJX'],
    name: 'T. Rowe Price Retirement 2035 Fund',
    issuer: 'T. Rowe Price',
    stock: 73.6, bond: 21.8, cash: 4.2,
    citation: 'T. Rowe Price fund page — https://www.troweprice.com/personal-investing/tools/fund-research/TRRJX ; figures per Morningstar — https://www.morningstar.com/funds/xnas/trrjx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2035,
  },
  {
    family: ['TRRDX', 'TRPDX'],
    name: 'T. Rowe Price Retirement 2040 Fund',
    issuer: 'T. Rowe Price',
    stock: 86.75, bond: 13.25, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000002113 acc 0001099263-26-004427 (period 2026-02-28), FoF by underlying-fund name (31 holdings, sum 99.95): the ~5.98% Real Assets Fund-Z sleeve is EQUITY (REIT + resource stocks, TRP’s own classification) and counts as stock; cash folded to bond; normalized',
    directionalUntilPinned: false,
    asOf: '2026-02-28',
    tdfTargetYear: 2040,
  },
  {
    family: ['TRRKX', 'TRPKX'],
    name: 'T. Rowe Price Retirement 2045 Fund',
    issuer: 'T. Rowe Price',
    stock: 94.76, bond: 5.24, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000002110 acc 0001099263-26-004448 (period 2026-02-28), FoF by underlying-fund name (sum 99.99): Real Assets ~6.56% counted as the equity it is; cash folded to bond; normalized — matches TRP’s published glide anchor (~94%)',
    directionalUntilPinned: false,
    asOf: '2026-02-28',
    tdfTargetYear: 2045,
  },
  {
    family: ['TRRMX', 'TRPMX'],
    name: 'T. Rowe Price Retirement 2050 Fund',
    issuer: 'T. Rowe Price',
    stock: 97.3, bond: 2.7, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000014996 acc 0001099263-26-004449 (period 2026-02-28), FoF by underlying-fund name (sum 100.00): Real Assets ~6.77% counted as equity; cash folded to bond; normalized',
    directionalUntilPinned: false,
    asOf: '2026-02-28',
    tdfTargetYear: 2050,
  },
  {
    family: ['TRRNX', 'TRPNX'],
    name: 'T. Rowe Price Retirement 2055 Fund',
    issuer: 'T. Rowe Price',
    stock: 98.31, bond: 1.69, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000014997 acc 0001099263-26-004450 (period 2026-02-28), FoF by underlying-fund name (sum 100.00): Real Assets ~6.85% counted as equity; cash folded to bond; normalized — matches TRP’s published 98% long-end glide anchor',
    directionalUntilPinned: false,
    asOf: '2026-02-28',
    tdfTargetYear: 2055,
  },
  {
    family: ['TRRLX', 'TRPLX'],
    name: 'T. Rowe Price Retirement 2060 Fund',
    issuer: 'T. Rowe Price',
    stock: 98.29, bond: 1.71, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000045512 acc 0001099263-26-004422 (period 2026-02-28), FoF by underlying-fund name (sum 100.00): Real Assets ~6.85% counted as equity; cash folded to bond; normalized. The old committed 96.2 sat BELOW the 2055 row — a glide-path impossibility (2055 and 2060 both ride the ~98% max-equity plateau); the pin restores family coherence',
    directionalUntilPinned: false,
    asOf: '2026-02-28',
    tdfTargetYear: 2060,
  },
  {
    family: ['TRSJX', 'TRFKX'],
    name: 'T. Rowe Price Retirement 2065 Fund',
    issuer: 'T. Rowe Price',
    stock: 96.1, bond: 1.6, cash: 1.7,
    citation: 'T. Rowe Price fund page — https://www.troweprice.com/personal-investing/tools/fund-research/TRSJX ; figures per Morningstar/AAII — https://www.morningstar.com/funds/xnas/trsjx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2065,
  },
  {
    family: ['TRRIX', 'TRJWX'],
    name: 'T. Rowe Price Retirement Balanced Fund',
    issuer: 'T. Rowe Price',
    stock: 39.5, bond: 54.2, cash: 6.1,
    citation: 'T. Rowe Price fund page — https://www.troweprice.com/personal-investing/tools/fund-research/TRRIX ; figures per AAII/Morningstar — https://www.morningstar.com/funds/xnas/trrix/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
  },
  {
    family: ['RFDTX'],
    name: 'American Funds 2025 Target Date Retirement Income Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 46.2, bond: 47.4, cash: 6,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfdtx ; cross-check Schwab fund report card RFDTX',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2025,
  },
  {
    family: ['RFETX'],
    name: 'American Funds 2030 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 54.3, bond: 39.9, cash: 5.4,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfetx',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2030,
  },
  {
    family: ['RFFTX'],
    name: 'American Funds 2035 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 64.3, bond: 30.4, cash: 4.9,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfftx',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2035,
  },
  {
    family: ['RFGTX'],
    name: 'American Funds 2040 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 78, bond: 17.8, cash: 3.8,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfgtx',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2040,
  },
  {
    family: ['RFHTX'],
    name: 'American Funds 2045 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 85.6, bond: 10.8, cash: 3.2,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfhtx ; figures per AAII look-through',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2045,
  },
  {
    family: ['RFITX'],
    name: 'American Funds 2050 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 87.9, bond: 8.7, cash: 3.1,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfitx ; figures per AAII look-through',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2050,
  },
  {
    family: ['RFKTX'],
    name: 'American Funds 2055 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 89.1, bond: 7.7, cash: 2.9,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfktx ; figures per AAII look-through',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2055,
  },
  {
    family: ['RFUTX'],
    name: 'American Funds 2060 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 88, bond: 6, cash: 6,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfutx',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2060,
  },
  {
    family: ['RFVTX'],
    name: 'American Funds 2065 Target Date Retirement Fund (R6)',
    issuer: 'Capital Group / American Funds',
    stock: 89.5, bond: 7.4, cash: 2.8,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/rfvtx ; figures per AAII look-through',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2065,
  },
  {
    family: ['AGTHX', 'RGAGX'],
    name: 'The Growth Fund of America (A + R6)',
    issuer: 'Capital Group / American Funds',
    stock: 98, bond: 0, cash: 2,
    citation: 'Capital Group fund page asset mix — https://www.capitalgroup.com/individual/investments/funds/agthx',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
  },
  {
    family: ['ABALX', 'RLBGX'],
    name: 'American Balanced Fund (A + R6)',
    issuer: 'Capital Group / American Funds',
    stock: 58.6, bond: 32.4, cash: 6.2,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/abalx ; figures per Morningstar look-through — https://www.morningstar.com/funds/xnas/abalx/quote',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['AWSHX', 'RWMGX'],
    name: 'Washington Mutual Investors Fund (A + R6)',
    issuer: 'Capital Group / American Funds',
    stock: 96.5, bond: 0, cash: 3.5,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/awshx',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['AEPGX', 'RERGX'],
    name: 'EUPAC Fund (formerly EuroPacific Growth) (A + R6)',
    issuer: 'Capital Group / American Funds',
    stock: 94.5, bond: 0, cash: 4.7,
    citation: 'Capital Group fund page — https://www.capitalgroup.com/individual/investments/funds/aepgx ; figures per AAII/Morningstar look-through',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['SSFOX'],
    name: 'State Street Target Retirement Fund (income/landing fund, Class K)',
    issuer: 'State Street Global Advisors',
    stock: 30.13, bond: 69.87, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000046033 acc 0001410368-26-055457 (period 2026-03-31), FoF by underlying-fund name (13 underlyings, raw sum 101.45): equity 25.83 + SPDR DJ Global Real Estate 4.74 (REIT EQUITIES → stock) = 30.57 stock / bond 63.08 / cash 4.55 / commodity-futures 3.26 (denominator only, per the table convention); normalized 30.13. SSGA design statement: ~35% stocks+real estate at the landing allocation',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
  },
  {
    family: ['SSBSX'],
    name: 'State Street Target Retirement 2025 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 40.88, bond: 59.12, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC 485BPOS acc 0001193125-26-177471 (prospectus dated 2026-04-30) strategic-target table: equity funds 35.88 + DJ Global Real Estate 5.00 (REIT EQUITIES → stock) = 40.88 stock / bond funds 55.63 / commodity-futures 3.50 (denominator only); table sums 100.01; normalized 40.88',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2025,
  },
  {
    family: ['SSBYX'],
    name: 'State Street Target Retirement 2030 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 55.3, bond: 41.6, cash: 2.8,
    citation: 'SSGA fund fact sheet (ssga.com); figures per AAII/Morningstar — https://www.morningstar.com/funds/xnas/ssbyx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2030,
  },
  {
    family: ['SSCQX'],
    name: 'State Street Target Retirement 2040 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 73.9, bond: 23.8, cash: 2.2,
    citation: 'SSGA fund fact sheet (ssga.com); figures per AAII/Morningstar — https://www.morningstar.com/funds/xnas/sscqx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2040,
  },
  {
    family: ['SSDEX'],
    name: 'State Street Target Retirement 2045 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 80.3, bond: 17.5, cash: 2.2,
    citation: 'SSGA fund fact sheet (ssga.com); figures per AAII/Morningstar — https://www.morningstar.com/funds/xnas/ssdex/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2045,
  },
  {
    family: ['SSDLX'],
    name: 'State Street Target Retirement 2050 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 85.1, bond: 12.7, cash: 2.1,
    citation: 'SSGA fund fact sheet (ssga.com); figures per AAII/Morningstar — https://www.morningstar.com/funds/xnas/ssdlx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2050,
  },
  {
    family: ['SSDQX'],
    name: 'State Street Target Retirement 2055 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 88.2, bond: 9.6, cash: 2.1,
    citation: 'SSGA fund fact sheet (ssga.com); figures per AAII/Morningstar — https://www.morningstar.com/funds/xnas/ssdqx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2055,
  },
  {
    family: ['SSDYX'],
    name: 'State Street Target Retirement 2060 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 88.7, bond: 9.6, cash: 1.6,
    citation: 'SSGA fund fact sheet (ssga.com); figures per AAII/Morningstar — https://www.morningstar.com/funds/xnas/ssdyx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2060,
  },
  {
    family: ['SSFKX'],
    name: 'State Street Target Retirement 2065 Fund (Class K)',
    issuer: 'State Street Global Advisors',
    stock: 88.9, bond: 9.5, cash: 1.5,
    citation: 'SSGA fund fact sheet (ssga.com); figures per Morningstar — https://www.morningstar.com/funds/xnas/ssfkx/portfolio',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2065,
  },
  {
    family: ['JIYBX'],
    name: 'JPMorgan SmartRetirement Blend Income Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 40.3, bond: 54.4, cash: 5.2,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar/AAII — https://www.morningstar.com/funds/xnas/jiybx/quote',
    directionalUntilPinned: false,
    asOf: '2026-05-08',
  },
  {
    family: ['JRBYX'],
    name: 'JPMorgan SmartRetirement Blend 2030 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 52.74, bond: 47.26, cash: 0,
    citation: 'PINNED 2026-06-11 — SEC N-PORT-P S000037366 acc 0002071691-26-012762 (period 2026-03-31, the committed row’s own as-of), FoF by underlying-fund name + the direct fixed-income book (Treasuries/MBS/ABS): equity 52.61 / bond 47.14, sum 99.75; normalized 52.74. The old 56.26 matched NO period (prior-period reconstructions: 55.28 @2025-03, 55.87 @2025-09) — stale/miscomputed at its own date',
    directionalUntilPinned: false,
    asOf: '2026-03-31',
    tdfTargetYear: 2030,
  },
  {
    family: ['JPYRX'],
    name: 'JPMorgan SmartRetirement Blend 2035 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 67.9, bond: 28.4, cash: 3.5,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar/AAII',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2035,
  },
  {
    family: ['JOBYX'],
    name: 'JPMorgan SmartRetirement Blend 2040 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 78.3, bond: 18.8, cash: 2.8,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar/AAII — https://www.morningstar.com/funds/xnas/jobyx/quote',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2040,
  },
  {
    family: ['JMYAX'],
    name: 'JPMorgan SmartRetirement Blend 2045 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 85.2, bond: 12, cash: 2.7,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar/AAII',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2045,
  },
  {
    family: ['JNYAX'],
    name: 'JPMorgan SmartRetirement Blend 2050 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 90.5, bond: 7.1, cash: 2.3,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar — https://www.morningstar.com/funds/xnas/jnyax/quote',
    directionalUntilPinned: false,
    asOf: '2026-04-30',
    tdfTargetYear: 2050,
  },
  {
    family: ['JTYBX'],
    name: 'JPMorgan SmartRetirement Blend 2055 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 90.4, bond: 7.1, cash: 2.4,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar/AAII',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2055,
  },
  {
    family: ['JAAYX'],
    name: 'JPMorgan SmartRetirement Blend 2060 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 89.1, bond: 7.5, cash: 3.3,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar/AAII — https://www.morningstar.com/funds/xnas/jaayx/quote',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2060,
  },
  {
    family: ['JSBYX'],
    name: 'JPMorgan SmartRetirement Blend 2065 Fund (R6)',
    issuer: 'J.P. Morgan Asset Management',
    stock: 90.3, bond: 6.9, cash: 2.8,
    citation: 'J.P. Morgan Asset Management fund page (am.jpmorgan.com); figures per Morningstar/AAII — https://www.morningstar.com/funds/xnas/jsbyx/quote',
    directionalUntilPinned: false,
    asOf: '2026-05-31',
    tdfTargetYear: 2065,
  },
]

/** The table's aggregate static-snapshot as-of (P3·U13 — the date-surface vintage clock).
 *  DERIVED as the max per-row `asOf` (ISO strings compare lexicographically), so a refresh
 *  pass that re-dates any row moves the aggregate with zero re-typing (single-source — the
 *  blend gate's discipline). Rows without `asOf` (pure index funds whose allocation is
 *  definitional) don't hold the aggregate back. Fails loud if NO row carries a date — an
 *  undated snapshot table has no vintage to stamp (burned/062: no plausible default). */
export const BLEND_SNAPSHOT_AS_OF: string = TICKER_BLEND_ROWS.reduce<string>((max, row) => {
  return row.asOf !== undefined && row.asOf > max ? row.asOf : max
}, '') || (() => {
  throw new Error('[tickerBlend] no row carries an asOf date — the snapshot vintage is unstampable')
})()

/** Eager module-level ticker index (ai-journey-stats/003 — never minted in render).
 *  A duplicate ticker across families is a transcription bug: fail loud at module
 *  init, never first-row-wins. */
const buildTickerIndex = (): ReadonlyMap<string, TickerBlendRow> => {
  const index = new Map<string, TickerBlendRow>()
  for (const row of TICKER_BLEND_ROWS) {
    for (const ticker of row.family) {
      const key = ticker.toUpperCase()
      if (index.has(key)) {
        throw new Error(`[tickerBlend] duplicate ticker ${key} across families — transcription bug`)
      }
      index.set(key, row)
    }
  }
  return index
}

const TICKER_INDEX = buildTickerIndex()

/** Case-insensitive family lookup. `undefined` = unrecognized — intake routes to the
 *  manual classifier (D1); never a default blend (burned/062). */
export const findBlendRow = (ticker: string): TickerBlendRow | undefined =>
  TICKER_INDEX.get(ticker.trim().toUpperCase())

/** Collapse a {stock, bond, cash} blend to the engine's single stock weight:
 *  `stock / (stock + bond + cash)` — the bond sleeve absorbs cash (v1, 2-asset
 *  engine; plan §5), and dividing by the ACTUAL sum distributes an issuer "other"
 *  sleeve pro-rata. Finiteness FIRST (insight 010): a NaN/negative component or a
 *  zero-sum blend is incomputable — throw, never a default (burned/062). */
export const stockWeightForBlend = (blend: {
  readonly stock: number
  readonly bond: number
  readonly cash: number
}): number => {
  const { stock, bond, cash } = blend
  if (![stock, bond, cash].every((x) => Number.isFinite(x) && x >= 0)) {
    throw new Error(
      `[tickerBlend] blend components must be finite and ≥ 0 (got ${stock}/${bond}/${cash}) — finiteness before any arithmetic (insight 010)`,
    )
  }
  const total = stock + bond + cash
  if (total <= 0) {
    throw new Error('[tickerBlend] blend sums to zero — nothing to collapse; no default (burned/062)')
  }
  return stock / total
}
