/**
 * Asset Processor — Phase 1
 *
 * Reads raw PNGs from assets/raw/, optimizes them, builds a car sprite atlas,
 * and generates a typed manifest at src/assets/manifest.ts.
 *
 * Usage:
 *   pnpm run process-assets          — process all assets
 *   pnpm run process-assets:check    — verify committed outputs match pipeline (CI mode)
 */

import fs from 'node:fs';
import path from 'node:path';
import { optimizePng, buildAtlas, generateSpritesheetJson } from './image-processing';
import { ASSET_PROMPTS } from './asset-prompts';

const ROOT = path.resolve(import.meta.dirname, '..');
const RAW_DIR = path.join(ROOT, 'assets', 'raw');
const OUTPUT_DIR = path.join(ROOT, 'public', 'assets');
const MANIFEST_PATH = path.join(ROOT, 'src', 'assets', 'manifest.ts');

const CHECK_MODE = process.argv.includes('--check');

// --- Asset name validation (prevent code injection in generated TS) ---
const SAFE_NAME = /^[a-z0-9-]+$/;

// --- Category mappings ---
interface AssetMapping {
  rawName: string;
  category: 'sprites' | 'tracks' | 'textures' | 'ui';
  outputName: string;
  expectedWidth: number;
  expectedHeight: number;
}

const CAR_SPRITES = ['car-player-red', 'car-player-blue', 'car-player-yellow', 'car-ai'] as const;

function buildAssetMappings(): AssetMapping[] {
  const mappings: AssetMapping[] = [];
  for (const prompt of ASSET_PROMPTS) {
    let category: AssetMapping['category'];
    if (prompt.name.startsWith('car-')) {
      category = 'sprites';
    } else if (prompt.name.startsWith('track')) {
      category = 'tracks';
    } else if (prompt.name === 'menu-bg') {
      category = 'ui';
    } else {
      category = 'textures';
    }
    mappings.push({
      rawName: prompt.name,
      category,
      outputName: `${prompt.name}.png`,
      expectedWidth: prompt.targetWidth,
      expectedHeight: prompt.targetHeight,
    });
  }
  return mappings;
}

// --- Path jail: ensure resolved path is under allowed directory ---
function assertPathUnder(filePath: string, allowedDir: string): void {
  const resolved = path.resolve(filePath);
  const resolvedDir = path.resolve(allowedDir);
  if (!resolved.startsWith(resolvedDir + path.sep) && resolved !== resolvedDir) {
    throw new Error(`Path jail violation: ${resolved} is not under ${resolvedDir}`);
  }
}

// --- Manifest generation ---
function generateManifest(): string {
  const lines: string[] = [
    '/* eslint-disable */',
    '// @generated by scripts/process-assets.ts — DO NOT EDIT',
    '// Regenerate with: pnpm run process-assets',
    '',
    'export const ASSETS = {',
    '  cars: {',
    "    atlas: 'assets/sprites/cars-atlas.json',",
    '    frames: {',
    "      playerRed: 'car-player-red',",
    "      playerBlue: 'car-player-blue',",
    "      playerYellow: 'car-player-yellow',",
    "      ai: 'car-ai',",
    '    },',
    '  },',
    '  tracks: {',
    "    'track-01': { bg: 'assets/tracks/track01-bg.png' },",
    "    'track-02': { bg: 'assets/tracks/track02-bg.png' },",
    "    'track-03': { bg: 'assets/tracks/track03-bg.png' },",
    '  },',
    '  textures: {',
    "    asphalt: 'assets/textures/asphalt-tile.png',",
    "    grass: 'assets/textures/grass-tile.png',",
    "    curb: 'assets/textures/curb-tile.png',",
    '  },',
    '  ui: {',
    "    menuBg: 'assets/ui/menu-bg.png',",
    '  },',
    '} as const;',
    '',
    "export type PlayerCarFrame = typeof ASSETS.cars.frames[Exclude<keyof typeof ASSETS.cars.frames, 'ai'>];",
    "export type AiCarFrame = typeof ASSETS.cars.frames['ai'];",
    'export type CarFrame = PlayerCarFrame | AiCarFrame;',
    'export type TrackId = keyof typeof ASSETS.tracks;',
    '',
  ];
  return lines.join('\n');
}

// --- Main pipeline ---
async function main(): Promise<void> {
  console.log(CHECK_MODE ? '=== Asset Processor (CHECK mode) ===' : '=== Asset Processor ===');

  const mappings = buildAssetMappings();

  // Step 0: Validate asset names
  for (const m of mappings) {
    if (!SAFE_NAME.test(m.rawName)) {
      throw new Error(`Invalid asset name "${m.rawName}" — must match /^[a-z0-9-]+$/`);
    }
  }

  // Step 1: Validate raw assets exist
  console.log('\n[1/7] Validating raw assets...');
  const missing: string[] = [];
  for (const m of mappings) {
    const rawPath = path.join(RAW_DIR, `${m.rawName}.png`);
    if (!fs.existsSync(rawPath)) {
      missing.push(m.rawName);
    }
  }
  if (missing.length > 0) {
    console.error(`Missing raw assets: ${missing.join(', ')}`);
    console.error('Run `pnpm run generate-assets` to generate raw assets first.');
    process.exit(1);
  }
  console.log(`  ✓ All ${mappings.length} raw assets found`);

  if (CHECK_MODE) {
    // In check mode: generate everything in memory and compare to existing files
    await runCheckMode(mappings);
    return;
  }

  // Step 2: Clean output directory
  console.log('\n[2/7] Cleaning output directory...');
  if (fs.existsSync(OUTPUT_DIR)) {
    fs.rmSync(OUTPUT_DIR, { recursive: true });
  }
  console.log('  ✓ Cleaned public/assets/');

  // Step 3: Create directory structure
  console.log('\n[3/7] Creating directory structure...');
  const subdirs = ['sprites', 'tracks', 'textures', 'ui'];
  for (const sub of subdirs) {
    const dir = path.join(OUTPUT_DIR, sub);
    assertPathUnder(dir, OUTPUT_DIR);
    fs.mkdirSync(dir, { recursive: true });
  }
  console.log('  ✓ Created subdirectories');

  // Step 4: Optimize individual assets
  console.log('\n[4/7] Optimizing assets...');
  const nonCarMappings = mappings.filter((m) => !m.rawName.startsWith('car-'));
  for (const m of nonCarMappings) {
    const rawPath = path.join(RAW_DIR, `${m.rawName}.png`);
    const outPath = path.join(OUTPUT_DIR, m.category, m.outputName);
    assertPathUnder(outPath, OUTPUT_DIR);
    await optimizePng(rawPath, outPath);
    const rawSize = fs.statSync(rawPath).size;
    const outSize = fs.statSync(outPath).size;
    console.log(`  ✓ ${m.rawName}: ${fmtSize(rawSize)} → ${fmtSize(outSize)}`);
  }

  // Step 5: Build car sprite atlas
  console.log('\n[5/7] Building car sprite atlas...');
  const carInputs = CAR_SPRITES.map((name) => path.join(RAW_DIR, `${name}.png`));
  const atlasPath = path.join(OUTPUT_DIR, 'sprites', 'cars-atlas.png');
  assertPathUnder(atlasPath, OUTPUT_DIR);
  const atlasDims = await buildAtlas(carInputs, atlasPath, 2, 2, 256, 256, 2);
  console.log(`  ✓ Atlas: ${atlasDims.width}×${atlasDims.height}`);

  // Generate spritesheet JSON
  const spritesheetJson = generateSpritesheetJson(
    [...CAR_SPRITES],
    2,
    256,
    256,
    2,
    atlasDims.width,
    atlasDims.height,
    'cars-atlas.png',
  );
  const jsonPath = path.join(OUTPUT_DIR, 'sprites', 'cars-atlas.json');
  assertPathUnder(jsonPath, OUTPUT_DIR);
  fs.writeFileSync(jsonPath, JSON.stringify(spritesheetJson, null, 2) + '\n');
  console.log('  ✓ Spritesheet JSON written');

  // Step 6: Generate manifest
  console.log('\n[6/7] Generating manifest...');
  const manifestDir = path.dirname(MANIFEST_PATH);
  if (!fs.existsSync(manifestDir)) {
    fs.mkdirSync(manifestDir, { recursive: true });
  }
  const manifestContent = generateManifest();
  fs.writeFileSync(MANIFEST_PATH, manifestContent);
  console.log('  ✓ src/assets/manifest.ts written');

  // Step 7: Validate outputs
  console.log('\n[7/7] Validating outputs...');
  let errors = 0;

  // Verify all non-car assets exist
  for (const m of nonCarMappings) {
    const outPath = path.join(OUTPUT_DIR, m.category, m.outputName);
    if (!fs.existsSync(outPath)) {
      console.error(`  ✗ Missing: ${m.category}/${m.outputName}`);
      errors++;
    }
  }

  // Verify atlas files
  if (!fs.existsSync(atlasPath)) {
    console.error('  ✗ Missing: sprites/cars-atlas.png');
    errors++;
  }
  if (!fs.existsSync(jsonPath)) {
    console.error('  ✗ Missing: sprites/cars-atlas.json');
    errors++;
  }

  // Verify atlas JSON structure
  const loadedJson = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  for (const name of CAR_SPRITES) {
    if (!loadedJson.frames[name]) {
      console.error(`  ✗ Missing atlas frame: ${name}`);
      errors++;
    }
  }
  if (!loadedJson.meta?.image || !loadedJson.meta?.scale) {
    console.error('  ✗ Atlas JSON meta incomplete');
    errors++;
  }

  // Verify manifest exists
  if (!fs.existsSync(MANIFEST_PATH)) {
    console.error('  ✗ Missing: src/assets/manifest.ts');
    errors++;
  }

  if (errors > 0) {
    console.error(`\n${errors} validation error(s)`);
    process.exit(1);
  }

  // Summary
  console.log('\n=== Summary ===');
  const totalFiles = nonCarMappings.length + 2 + 1; // individual + atlas png/json + manifest
  console.log(`  Files generated: ${totalFiles}`);
  console.log(`  Atlas: ${atlasDims.width}×${atlasDims.height} (${CAR_SPRITES.length} sprites)`);
  console.log('  Manifest: src/assets/manifest.ts');
  console.log('  ✓ All outputs valid');
}

async function runCheckMode(mappings: AssetMapping[]): Promise<void> {
  let diffs = 0;

  // Check manifest
  console.log('\nChecking manifest...');
  const expectedManifest = generateManifest();
  if (!fs.existsSync(MANIFEST_PATH)) {
    console.error('  ✗ Manifest does not exist');
    diffs++;
  } else {
    const actual = fs.readFileSync(MANIFEST_PATH, 'utf-8');
    if (actual !== expectedManifest) {
      console.error('  ✗ Manifest content differs');
      diffs++;
    } else {
      console.log('  ✓ Manifest matches');
    }
  }

  // Check that all output files exist
  console.log('\nChecking output files...');
  const nonCarMappings = mappings.filter((m) => !m.rawName.startsWith('car-'));
  for (const m of nonCarMappings) {
    const outPath = path.join(OUTPUT_DIR, m.category, m.outputName);
    if (!fs.existsSync(outPath)) {
      console.error(`  ✗ Missing: ${m.category}/${m.outputName}`);
      diffs++;
    }
  }

  const atlasPath = path.join(OUTPUT_DIR, 'sprites', 'cars-atlas.png');
  const jsonPath = path.join(OUTPUT_DIR, 'sprites', 'cars-atlas.json');
  if (!fs.existsSync(atlasPath)) {
    console.error('  ✗ Missing: sprites/cars-atlas.png');
    diffs++;
  }
  if (!fs.existsSync(jsonPath)) {
    console.error('  ✗ Missing: sprites/cars-atlas.json');
    diffs++;
  }

  if (diffs > 0) {
    console.error(`\n${diffs} difference(s) found. Run \`pnpm run process-assets\` to regenerate.`);
    process.exit(1);
  }

  console.log('\n  ✓ All outputs match — no regeneration needed');
}

function fmtSize(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
}

main().catch((err) => {
  console.error('Asset processor failed:', err);
  process.exit(1);
});
