export const WORLD = {
  TILE_SIZE: 32,
} as const satisfies Record<string, number>;

export const SIMULATION = {
  FIXED_DT_S: 1 / 60,
  FIXED_DT_MS: (1 / 60) * 1000,
  MAX_DELTA_MS: 200,
  MAX_CATCHUP_TICKS: 5,
} as const satisfies Record<string, number>;

export const MOVEMENT = {
  RUN_SPEED: 200,
  WALK_SPEED: 100,
  SNEAK_SPEED: 40,
  JUMP_VELOCITY: -350,
  SLIDE_SPEED: 220,
  SLIDE_DURATION_S: 0.8,
  GRAVITY: 800,
} as const satisfies Record<string, number>;

export const NOISE = {
  RUN_LEVEL: 1.0,
  WALK_LEVEL: 0.5,
  SNEAK_LEVEL: 0.05,
  JUMP_LAND_LEVEL: 0.7,
  SLIDE_LEVEL: 0.3,
  DOOR_LEVEL: 0.6,
  ELEVATOR_DING_LEVEL: 1.0,
  THROWABLE_IMPACT_LEVEL: 0.8,
  PHONE_RING_LEVEL: 0.7,
  GASP_LEVEL: 0.4,
  LIGHTER_FLICK_LEVEL: 0.5,
  CARPET_MULT: 0.4,
  WOOD_MULT: 1.0,
  TILE_MULT: 1.3,
  ADJACENT_ROOM_OPEN_DOOR: 0.7,
  ADJACENT_ROOM_CLOSED_DOOR: 0.2,
  CROSS_FLOOR: 0.05,
  ELEVATOR_SHAFT: 0.3,
  PROPAGATION_THRESHOLD: 0.01,
} as const satisfies Record<string, number>;

export const ESCAPE = {
  FIRST_WINDOW_AT_S: 90,
  REPEAT_INTERVAL_S: 60,
  WARNING_BEFORE_S: 15,
  WINDOW_DURATION_NIGHT_1_S: 20,
  WINDOW_DURATION_NIGHT_2_S: 18,
  WINDOW_DURATION_NIGHT_3_S: 15,
  WINDOW_DURATION_NIGHT_4_S: 12,
  WINDOW_DURATION_NIGHT_5_S: 10,
} as const satisfies Record<string, number>;

export const MONSTER = {
  BELLHOP_SPEED: 250,
  BELLHOP_HEARING_THRESHOLD: 0.15,
  BELLHOP_ALERT_THRESHOLD: 0.3,
  BELLHOP_INVESTIGATE_S: 5,
  BELLHOP_CONFUSED_S: 3,
  CATCH_RADIUS: 24,
  HOUSEKEEPER_SPEED: 60,
  HOUSEKEEPER_CHECK_DURATION_S: 4,
  HOUSEKEEPER_SKIP_PAUSE_S: 1,
  GUEST_LUNGE_SPEED: 400,
  GUEST_LUNGE_RANGE_TILES: 4,
  GUEST_DETECT_RANGE_TILES: 2,
  GUEST_RESET_COOLDOWN_S: 10,
  GUEST_GLOW_VISIBLE_LIGHT_THRESHOLD: 0.4,
  GUEST_GLOW_VISIBLE_RANGE_TILES: 3,
  GUEST_GLOW_LIGHTER_RANGE_TILES: 4,
  NIGHT_4_SPEED_MULT: 1.25,
  BELLHOP_CATCH_DURATION_S: 2.5,
  HOUSEKEEPER_CATCH_DURATION_S: 2.5,
  GUEST_CATCH_DURATION_S: 2.5,
} as const satisfies Record<string, number>;

export const BREATH = {
  BASE_DURATION_S: 8,
  RHYTHM_EXTEND_S: 3,
  RHYTHM_WINDOW_MS: 200,
} as const satisfies Record<string, number>;

export const INVENTORY = {
  THROWABLE_CARRY_LIMIT: 3,
  DND_SIGNS_PER_NIGHT: 3,
  LIGHTER_CHARGE_S: 30,
  LIGHTER_CHARGES_PER_NIGHT: 2,
} as const satisfies Record<string, number>;

export const CAMERA = {
  LEAD_DISTANCE: 80,
  FOLLOW_LERP: 0.08,
  HIDE_ZOOM: 1.4,
  ZOOM_DURATION_MS: 300,
  SHAKE_DURATION_MS: 150,
  SHAKE_INTENSITY: 0.005,
  HORROR_HOLD_MS: 800,
} as const satisfies Record<string, number>;

export const LIGHTING = {
  SCONCE_FLICKER_MIN: 0.8,
  SCONCE_FLICKER_MAX: 1.0,
  SCONCE_FLICKER_SPEED: 2.0,
  LIGHTNING_MIN_INTERVAL_MS: 15000,
  LIGHTNING_MAX_INTERVAL_MS: 45000,
  LIGHTNING_FLASH_MS: 200,
  LIGHTNING_FADE_MS: 500,
  LIGHT_UNDER_DOOR_WIDTH: 4,
  LIGHT_SOURCE_DEFAULT_RADIUS: 80,
  LIGHTER_RADIUS: 120,
} as const satisfies Record<string, number>;

export const TOOLS = {
  THROW_DISTANCE: 200,
  THROW_PICKUP_RANGE: 32,
} as const satisfies Record<string, number>;

export const PHONE = {
  RING_DURATION_S: 15,
  GRACE_PERIOD_S: 5,
  RHYTHM_INTERVAL_S: 2,
  RHYTHM_WINDOW_MS: 200,
} as const satisfies Record<string, number>;
