/* eslint-disable */
// @generated by scripts/process-assets.ts — DO NOT EDIT
// Regenerate with: pnpm run process-assets

export const ASSETS = {
  cars: {
    atlas: 'assets/sprites/cars-atlas.json',
    frames: {
      playerRed: 'car-player-red',
      playerBlue: 'car-player-blue',
      playerYellow: 'car-player-yellow',
      ai: 'car-ai',
    },
  },
  tracks: {
    'track-01': { bg: 'assets/tracks/track01-bg.png' },
    'track-02': { bg: 'assets/tracks/track02-bg.png' },
    'track-03': { bg: 'assets/tracks/track03-bg.png' },
  },
  textures: {
    asphalt: 'assets/textures/asphalt-tile.png',
    grass: 'assets/textures/grass-tile.png',
    curb: 'assets/textures/curb-tile.png',
  },
} as const;

export type PlayerCarFrame = typeof ASSETS.cars.frames[Exclude<keyof typeof ASSETS.cars.frames, 'ai'>];
export type AiCarFrame = typeof ASSETS.cars.frames['ai'];
export type CarFrame = PlayerCarFrame | AiCarFrame;
export type TrackId = keyof typeof ASSETS.tracks;
