/**
 * Generate `src/lib/gameplay-clip-source.ts` — a TS constant that
 * resolves at build time to whichever of `public/trailer/gameplay.mp4`
 * (Phase 5 real clip) or `public/trailer/gameplay-placeholder.mp4`
 * (Phase 4 stand-in) exists. S05_GameplayDissolve imports the constant
 * and passes it through `staticFile()` — the scene file itself MUST
 * NOT call `existsSync` because Remotion bundles scene files for
 * browser-context rendering where `node:fs` is unavailable (would
 * crash at render time).
 *
 * Wired into the trailer package.json lifecycle:
 *   - `postinstall` (first clone gets a valid constant before any
 *     `pnpm studio` / `pnpm render` runs and fails module resolution)
 *   - `prerender` + `prestudio` (regenerate on every Remotion invocation
 *     so the constant tracks current filesystem state — i.e. picks up
 *     `gameplay.mp4` automatically the moment Phase 5 lands it locally)
 *
 * The generated TS file IS committed (NOT gitignored). Default body
 * points at the placeholder; `git status` may show drift after this
 * script regenerates against a local `gameplay.mp4`. That drift is
 * intentional state — reset to placeholder via `pnpm sync-gameplay`
 * against a missing real clip before any commit that isn't promoting
 * Phase 5 ship.
 *
 * Path resolution uses `fileURLToPath(import.meta.url) + resolve(...)`
 * per insight #057.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
// scripts/ -> videos/trailer/ -> videos/ -> BURNED root
const BURNED_ROOT = resolve(__dirname, '..', '..', '..')

const REAL = resolve(BURNED_ROOT, 'public', 'trailer', 'gameplay.mp4')
const PLACEHOLDER = resolve(BURNED_ROOT, 'public', 'trailer', 'gameplay-placeholder.mp4')
const OUT = resolve(__dirname, '..', 'src', 'lib', 'gameplay-clip-source.ts')

const hasReal = existsSync(REAL)
const hasPlaceholder = existsSync(PLACEHOLDER)

// staticFile() in trailer resolves against setPublicDir('../../public') — Phase 0 ADR #8.
// Paths exported here are RELATIVE to BURNED's public/ dir (ADR #15 partition).
const chosenStaticPath = hasReal ? 'trailer/gameplay.mp4' : 'trailer/gameplay-placeholder.mp4'
const isPlaceholder = !hasReal

if (!hasReal && !hasPlaceholder) {
  console.warn(`[sync-gameplay-clip] WARN: neither gameplay.mp4 nor gameplay-placeholder.mp4 exists`)
  console.warn(`  expected one of:`)
  console.warn(`    ${REAL}`)
  console.warn(`    ${PLACEHOLDER}`)
  console.warn(`  generating constant pointing at placeholder anyway — S05 render will 404 until you run \`pnpm gen:gameplay-placeholder\``)
}

const stamp = new Date().toISOString()
const body = `// GENERATED by videos/trailer/scripts/sync-gameplay-clip.ts on ${stamp}
// DO NOT EDIT — regenerated on every postinstall / prerender / prestudio.
// Source of truth: whichever of public/trailer/gameplay.mp4 (Phase 5 real clip)
// or public/trailer/gameplay-placeholder.mp4 (Phase 4 stand-in) exists at sync time.
// staticFile() resolves these against Phase 0 ADR #8 setPublicDir('../../public')
// — paths are relative to BURNED public/ per ADR #15 partition.
//
// Phase 5 swap workflow:
//   1. Phase 5 writes public/trailer/gameplay.mp4.new
//   2. pnpm verify:gameplay-clip ./public/trailer/gameplay.mp4.new
//   3. If gate passes: mv .new → gameplay.mp4
//   4. Next \`pnpm render\` / \`pnpm studio\` triggers prerender/prestudio,
//      which regenerates this file pointing at the real clip.
export const GAMEPLAY_CLIP_SOURCE = ${JSON.stringify(chosenStaticPath)} as const
export const GAMEPLAY_CLIP_IS_PLACEHOLDER = ${JSON.stringify(isPlaceholder)} as const
`

// Idempotency: skip write if body unchanged. Avoids spurious file mtime churn
// across lifecycle hooks that fire mid-render. Compares the line BELOW the
// timestamp header so re-runs at different times don't trigger spurious writes.
const newSig = `${chosenStaticPath}|${isPlaceholder}`
let prevSig = ''
if (existsSync(OUT)) {
  const prev = readFileSync(OUT, 'utf8')
  const m = prev.match(/GAMEPLAY_CLIP_SOURCE = "([^"]+)".*?GAMEPLAY_CLIP_IS_PLACEHOLDER = (true|false)/s)
  if (m) prevSig = `${m[1]}|${m[2]}`
}

if (prevSig === newSig) {
  console.log(`[sync-gameplay-clip] unchanged (${chosenStaticPath}${isPlaceholder ? ' [placeholder]' : ' [real]'})`)
} else {
  writeFileSync(OUT, body, 'utf8')
  console.log(`[sync-gameplay-clip] wrote ${OUT}`)
  console.log(`  -> ${chosenStaticPath} ${isPlaceholder ? '[placeholder]' : '[real]'}`)
}
