// AUTOGENERATED by scripts/generate-audio-manifest.ts (Unit 2.8) — do not edit by hand.
// Regenerate with: pnpm generate:manifest
// Source of truth: src/lib/script.ts BURNED_TRAILER_LINES + Unit 2.5 loudness audit + FFprobe.
import type { AudioAsset } from './audio-manifest-types.js';

export type { AudioAsset } from './audio-manifest-types.js';

export const AUDIO_ASSETS: readonly AudioAsset[] = [
  {
    "filename": "s01-cue-60-janet.wav",
    "staticPath": "trailer/audio/lines/s01-cue-60-janet.wav",
    "startFrame": 60,
    "actualFrames": 139,
    "voice": "janet",
    "expectedFrames": 150,
    "cueType": "cold-open",
    "leadFramesHint": 0,
    "loudnessLufs": -16.35,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "Inline [sarcastic] tag before 'Honestly' per Phase 0 Unit 0.3 cadence-spec.md. Voice settings override per COLD_OPEN_SPEAKER constant in scripts/cold-open-prototype.ts (Eleanor cunty-matriarch-tuned per Phase 2 Unit 2.3 re-lock: stability 0.40, similarity 0.75, style 0.45, speaker_boost true, speed 0.85). Voice ID 2qQJWjw5XdG80GreshqG (Shared Library)."
    }
  },
  {
    "filename": "s02-cue-219-dash.wav",
    "staticPath": "trailer/audio/lines/s02-cue-219-dash.wav",
    "startFrame": 219,
    "actualFrames": 357,
    "voice": "dash",
    "expectedFrames": 351,
    "cueType": "sustained",
    "leadFramesHint": 0,
    "loudnessLufs": -16.55,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "Sterling-CODED briefing-room formality; ellipsis pauses at clause boundaries; Roger defaults voice_settings."
    }
  },
  {
    "filename": "s03-cue-570-dash.wav",
    "staticPath": "trailer/audio/lines/s03-cue-570-dash.wav",
    "startFrame": 570,
    "actualFrames": 407,
    "voice": "dash",
    "expectedFrames": 270,
    "cueType": "sustained",
    "leadFramesHint": 0,
    "loudnessLufs": -16.38,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "[BEAT NNNms] markers expand to per-engine pause primitive (SSML <break time=\"NNNms\"/> or equivalent). 1.0s mid-scene dossier-page wipe to deck reveal happens AFTER this segment ends, before S03-deck begins."
    }
  },
  {
    "filename": "s03-cue-1007-dash.wav",
    "staticPath": "trailer/audio/lines/s03-cue-1007-dash.wav",
    "startFrame": 1007,
    "actualFrames": 362,
    "voice": "dash",
    "expectedFrames": 180,
    "cueType": "sustained",
    "leadFramesHint": 0,
    "loudnessLufs": -16.55,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "Trimmed from plan-original (~31w) to fit deadpan delivery in 6.0s budget. Cuts: 'of them' (implied by antecedent), 'exist to' + 'it' (compressed 'exist to help you survive it' → 'help you survive'), 'to' + final beat (compressed 'Or to ensure your colleagues don't' → 'Or ensure your colleagues don't' running with no preceding pause). Dark-closing gag preserved."
    }
  },
  {
    "filename": "s04-cue-1380-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-1380-dash.wav",
    "startFrame": 1380,
    "actualFrames": 55,
    "voice": "dash",
    "expectedFrames": 60,
    "cueType": "list",
    "leadFramesHint": 0,
    "loudnessLufs": -17.95,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]"
    }
  },
  {
    "filename": "s04-cue-1440-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-1440-dash.wav",
    "startFrame": 1440,
    "actualFrames": 106,
    "voice": "dash",
    "expectedFrames": 90,
    "cueType": "list",
    "leadFramesHint": 0,
    "loudnessLufs": -16.28,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]"
    }
  },
  {
    "filename": "s04-cue-1551-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-1551-dash.wav",
    "startFrame": 1551,
    "actualFrames": 132,
    "voice": "dash",
    "expectedFrames": 90,
    "cueType": "list",
    "leadFramesHint": 0,
    "loudnessLufs": -19.17,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "Trimmed from plan-original (~14w, 'who, for compliance reasons, is not named') to fit per-cue list-band sanity ceiling. 'name redacted for compliance' is in-character spy vocab; the em-dash carries the explanatory beat."
    }
  },
  {
    "filename": "s04-cue-1688-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-1688-dash.wav",
    "startFrame": 1688,
    "actualFrames": 137,
    "voice": "dash",
    "expectedFrames": 120,
    "cueType": "list",
    "leadFramesHint": 0,
    "loudnessLufs": -16.03,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]"
    }
  },
  {
    "filename": "s04-cue-1830-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-1830-dash.wav",
    "startFrame": 1830,
    "actualFrames": 152,
    "voice": "dash",
    "expectedFrames": 150,
    "cueType": "list",
    "leadFramesHint": 0,
    "loudnessLufs": -16.16,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]"
    }
  },
  {
    "filename": "s04-cue-1987-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-1987-dash.wav",
    "startFrame": 1987,
    "actualFrames": 133,
    "voice": "dash",
    "expectedFrames": 120,
    "cueType": "list",
    "leadFramesHint": 0,
    "loudnessLufs": -17.27,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]"
    }
  },
  {
    "filename": "s04-cue-2125-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-2125-dash.wav",
    "startFrame": 2125,
    "actualFrames": 174,
    "voice": "dash",
    "expectedFrames": 180,
    "cueType": "list",
    "leadFramesHint": 0,
    "loudnessLufs": -16.8,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "Otto 'on the research budget' phrasing matches ActRoster.tsx:153-158 source ('busy with the (unsanctioned, off-books, almost certainly illegal) research budget'). The 'Don't ask.' kicker is the deadpan glaze."
    }
  },
  {
    "filename": "s04-cue-2304-dash.wav",
    "staticPath": "trailer/audio/lines/s04-cue-2304-dash.wav",
    "startFrame": 2304,
    "actualFrames": 63,
    "voice": "dash",
    "expectedFrames": 60,
    "cueType": "payoff",
    "leadFramesHint": 2,
    "loudnessLufs": -17.21,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "R3 stacked-payoff truth-collision. Music ducks 2337→2367 (30 frames, 90%→30%). 3-frame silent hold 2367-2370 (last 12 frames of payoff VO play through the tail-fade-to-black; audio carries cinematically through the close). Cascade chrome at 30% IS the visual antecedent of 'they' (per Unit 1.5 SHOWING-beats-TELLING)."
    }
  },
  {
    "filename": "s05-cue-2610-dash.wav",
    "staticPath": "trailer/audio/lines/s05-cue-2610-dash.wav",
    "startFrame": 2610,
    "actualFrames": 118,
    "voice": "dash",
    "expectedFrames": 150,
    "cueType": "sustained",
    "leadFramesHint": 0,
    "loudnessLufs": -15.75,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "Sparse VO over live gameplay audio at 30% bed; em-dash pauses for sotto-voce conspiratorial register."
    }
  },
  {
    "filename": "s05-cue-2730-dash.wav",
    "staticPath": "trailer/audio/lines/s05-cue-2730-dash.wav",
    "startFrame": 2730,
    "actualFrames": 72,
    "voice": "dash",
    "expectedFrames": 50,
    "cueType": "scream",
    "leadFramesHint": 1,
    "loudnessLufs": -16,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[shouts]",
      "notes": "Sterling-LANA four-axis acoustic shape per Phase 0 Unit 0.6 cadence-spec.md §3.6: (1) flat pitch (no F0 falsetto rise), (2) 6-12 dB amplitude jump vs surrounding gameplay bed, (3) FIRST-vowel drag, (4) accent anchored on first syllable. Self-closing [shouts] tag (ElevenLabs v3 ONLY)."
    }
  },
  {
    "filename": "s06-cue-2910-dash.wav",
    "staticPath": "trailer/audio/lines/s06-cue-2910-dash.wav",
    "startFrame": 2910,
    "actualFrames": 157,
    "voice": "dash",
    "expectedFrames": 222,
    "cueType": "payoff",
    "leadFramesHint": 0,
    "loudnessLufs": -16.61,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[sarcastic]",
      "notes": "'Hold it tight' is the entendre setup line for Phrasing! — physical-action ambiguity per spec §3.5 earned-Phrasing! mechanic. BURNED logo lands at frame 3110 (during this line, mid-clause)."
    }
  },
  {
    "filename": "s06-cue-3144-dash.wav",
    "staticPath": "trailer/audio/lines/s06-cue-3144-dash.wav",
    "startFrame": 3144,
    "actualFrames": 19,
    "voice": "dash",
    "expectedFrames": 12,
    "cueType": "payoff",
    "leadFramesHint": 0,
    "loudnessLufs": -15.3,
    "cadenceAdapter": {
      "engine": "elevenlabs-v3",
      "prefixTag": "[excited]",
      "notes": "Interjective callback cadence — quick rise on 'Phra-', fall on '-sing.' (NOT the arrogant-briefer deadpan that suits the rest of Dash's cues). Resolver in elevenlabs.ts detects '[excited]' + voice='dash' and returns PHRASING_INTERJECTIVE_SETTINGS (stab 0.30 / style 0.65 / speed 1.05). FFmpeg fade curve: qsin (per plan Step 7). R15 #4 stamp 'OPERATION STATUS: FIELD-READY' lands at frame 3150 (concurrent with Phrasing audio tail). R15 #5 closing-card lands at frame 3165 (post-audio)."
    }
  }
] as const;
