// GENERATED by videos/trailer/scripts/sync-gameplay-clip.ts on 2026-05-24T02:14:56.601Z
// DO NOT EDIT — regenerated on every postinstall / prerender / prestudio.
// Source of truth: whichever of public/trailer/gameplay.mp4 (Phase 5 real clip)
// or public/trailer/gameplay-placeholder.mp4 (Phase 4 stand-in) exists at sync time.
// staticFile() resolves these against Phase 0 ADR #8 setPublicDir('../../public')
// — paths are relative to BURNED public/ per ADR #15 partition.
//
// Phase 5 swap workflow:
//   1. Phase 5 writes public/trailer/gameplay.mp4.new
//   2. pnpm verify:gameplay-clip ./public/trailer/gameplay.mp4.new
//   3. If gate passes: mv .new → gameplay.mp4
//   4. Next `pnpm render` / `pnpm studio` triggers prerender/prestudio,
//      which regenerates this file pointing at the real clip.
export const GAMEPLAY_CLIP_SOURCE = "trailer/gameplay-placeholder.mp4" as const
export const GAMEPLAY_CLIP_IS_PLACEHOLDER = true as const
